### PR TITLE
Dry::Struct#with method

### PR DESCRIPTION
**Pull request by Kukunin**
Since dry-struct immutable (and that's great), there should be a method to return new instance with applied changeset.

Currently I have a lot of `object.class[object.to_hash.merge(changeset)]` lines in my application, want to replace them with neat `object.with(changeset)`

### CODE REVIEW

**Comment by Kukunin** [comment]
@flash-gordon @solnic what do you think?

**Comment by flash-gordon** [comment]
yes, I agree, this is a common task. This also reminds Clojure's records, they implement `map`'s interface

**Comment by Kukunin** [comment]
@flash-gordon what's the next step in order to make it live? (and make some release, probably)

**Comment by solnic** [comment]
I've been using a convention that `#new` is for getting a new instance with new state, and `#with` is for getting a new instance with new *options*. WDYT about using `#new` here instead of `#with` since structs have no options?

**Comment by Kukunin** [comment]
actually, that works even better. In fact, we really use `.new` inside.

I'm going to rename

**Comment by Kukunin** [comment]
Btw, here is one flaw in design I have no idea how to resolve. I use some sum types in my system, just to better express intention.

```ruby
class UnresolvedItem < Dry::Struct
  attribute :resolution, Types::Strict::Nil
end
class ResolvedItem < Dry::Struct
  attribute :resolution, ItemResolution
end
Item = UnresolvedItem | ResolvedItem
```

and here I have

```ruby
unresolved_item = Item[resolution: nil]
resolved = unresolved_item.with(resolution: a_resolution)
```

And this doesn't work, because it tries to apply `{resolution: a_resolution}` to `UnresolvedItem` class, not `Item` sum type.

**Comment by flash-gordon** [comment]
@Kukunin you need to define your own `new` then that will use the sum type

**Comment by timriley** [comment]
I'm a little late to the party, but to me, `#new` feels a _little_ strange here. It doesn't "read" naturally, and it feels like this could be confused with the class-level constructor (`#new` is pretty uncommon as an instance method in Ruby libraries).

@solnic makes the distinction between _options_ and _state_, but since structs don't carry options, I don't feel like that distinction is actually all that important here. I'd much rather see `#with` stay, or if we like the word `new`, perhaps something like `#new_with`? To me, the "with" is what implied the merging. (heck, why don't we just use `#merge?`).

What do you think? Just trying to keep our API as natural as possible.

**Comment by backus** [comment]
+1 to what @timriley said. Out of curiosity I used pry to grep out `#with` and `#new` instance method definitions in dry-rb and rom-rb libraries to see if there is a clear convention. Seems like `#with` is wayyy more common:

```ruby
>> find-method with Dry
Dry::Logic::Operations::Abstract
Dry::Logic::Operations::Abstract#with
Dry::Logic::Rule
Dry::Logic::Rule#with
Dry::Logic::Rule#args_with_names
Dry::Types::Compiler
Dry::Types::Compiler#merge_with
Dry::Types::Hash
Dry::Types::Hash#strict_with_defaults
Dry::Types::Options
Dry::Types::Options#with
Dry::Validation::Guard
Dry::Validation::Guard#with
Dry::Validation::MessageCompiler
Dry::Validation::MessageCompiler#with
Dry::Validation::MessageCompiler::VisitorOpts
Dry::Validation::MessageCompiler::VisitorOpts#with_rule
Dry::Validation::Schema
Dry::Validation::Schema#with
Dry::Validation::Schema::DSL
Dry::Validation::Schema::DSL#with
Dry::Validation::Schema::Rule
Dry::Validation::Schema::Rule#with
Enumerable
Enumerable#each_with_index
Enumerable#each_with_object
>> find-method with ROM
ROM::Changeset
ROM::Changeset#with
ROM::Command
ROM::Command#with
ROM::Command#with_opts
ROM::CommandRegistry
ROM::CommandRegistry#with
ROM::Commands::Graph
ROM::Commands::Graph#with
ROM::Mapper::AttributeDSL
ROM::Mapper::AttributeDSL#with_attr_options
ROM::Mapper::AttributeDSL#with_name_or_options
ROM::Pipeline
ROM::Pipeline#map_with
ROM::Processor::Transproc
ROM::Processor::Transproc#with_row_proc
ROM::Relation
ROM::Relation#with
ROM::Relation::Graph
ROM::Relation::Graph#with_nodes
ROM::Relation::Name
ROM::Relation::Name#with
ROM::Repository::RelationProxy
ROM::Repository::RelationProxy#with
ROM::Repository::RelationProxy#map_with
ROM::Repository::RelationProxy::Combine
ROM::Repository::RelationProxy::Combine#combine_from_assoc_with_fallback
ROM::SQL::Association::ManyToMany
ROM::SQL::Association::ManyToMany#with_keys
ROM::SQL::Association::ManyToOne
ROM::SQL::Association::ManyToOne#with_keys
ROM::SQL::Association::OneToMany
ROM::SQL::Association::OneToMany#with_keys
ROM::SQL::Commands::Create
ROM::SQL::Commands::Create#with_input_tuples
ROM::SQL::Commands::Update
ROM::SQL::Commands::Update#with_input_tuples
ROM::SQL::Plugin::Associates::InstanceMethods
ROM::SQL::Plugin::Associates::InstanceMethods#with_association
ROM::Schema
ROM::Schema#with
>> find-method new Dry
Dry::Initializer::Attribute.new

Dry::Logic::Evaluator::Set.new

Dry::Logic::Operations::Check.new

Dry::Logic::Operations::Key.new

Dry::Struct::Value.new

Dry::Types::Constructor.new

Dry::Validation::Executor.new

Dry::Validation::MessageCompiler::VisitorOpts.new

Dry::Validation::Schema.new
Class
Class#new
Dry::Logic::Operations::Abstract
Dry::Logic::Operations::Abstract#new
Dry::Struct::ClassInterface
Dry::Struct::ClassInterface#new
Dry::Validation::PredicateRegistry
Dry::Validation::PredicateRegistry#new
Dry::Validation::Schema::Rule
Dry::Validation::Schema::Rule#new
Dry::Validation::Schema::Value
Dry::Validation::Schema::Value#new
>> find-method new ROM
Dry::Struct::Value.new

Etc::Group.new

Etc::Passwd.new

Process::Tms.new

ROM::Commands::Graph::Builder::Node::Command.new

ROM::Commands::Graph::Builder::Node::Restriction.new

ROM::SQL::Association.new
Dry::Struct::ClassInterface
Dry::Struct::ClassInterface#new
ROM::Changeset
ROM::Changeset#new
ROM::Command
ROM::Command#new
ROM::Mapper::AttributeDSL
ROM::Mapper::AttributeDSL#new
ROM::Processor::Transproc
ROM::Processor::Transproc#new
ROM::Relation
ROM::Relation#new
ROM::Relation::Curried
ROM::Relation::Curried#__new__
ROM::Relation::Loaded
ROM::Relation::Loaded#new
ROM::Relation::ViewDSL
ROM::Relation::ViewDSL#new_schema
ROM::Repository::RelationProxy
ROM::Repository::RelationProxy#__new__
ROM::Schema
ROM::Schema#new
```

Filtering down to real instance methods I these candidates:

- `Dry::Logic::Operations::Abstract#with`
- `Dry::Logic::Rule#with`
- `Dry::Types::Options#with`
- `Dry::Validation::Guard#with`
- `Dry::Validation::MessageCompiler#with`
- `Dry::Validation::Schema#with`
- `Dry::Validation::Schema::DSL#with`
- `Dry::Validation::Schema::Rule#with`
- `ROM::Changeset#with`
- `ROM::CommandRegistry#with`
- `ROM::Commands::Graph#with`
- `ROM::Relation#with`
- `ROM::Relation::Name#with`
- `ROM::Repository::RelationProxy#with`
- `ROM::Schema#with`
- `Dry::Logic::Operations::Abstract#new`
- `Dry::Validation::PredicateRegistry#new`
- `Dry::Validation::Schema::Rule#new`
- `Dry::Validation::Schema::Value#new`
- `ROM::Changeset#new`
- `ROM::Command#new`
- `ROM::Mapper::AttributeDSL#new`
- `ROM::Processor::Transproc#new`
- `ROM::Relation#new`
- `ROM::Relation::Loaded#new`
- `ROM::Relation::ViewDSL#new`
- `ROM::Schema#new`

Using Pry's `show-method` for each:

```ruby
>> show-method Dry::Logic::Operations::Abstract#with

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/dry-logic-0.4.1/lib/dry/logic/operations/abstract.rb @ line 34:
Owner: Dry::Logic::Operations::Abstract
Visibility: public
Number of lines: 3

def with(new_options)
  new(rules, options.merge(new_options))
end
>> show-method Dry::Logic::Rule#with

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/dry-logic-0.4.1/lib/dry/logic/rule.rb @ line 79:
Owner: Dry::Logic::Rule
Visibility: public
Number of lines: 3

def with(new_opts)
  self.class.new(predicate, options.merge(new_opts))
end
>> show-method Dry::Types::Options#with

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/dry-types-0.9.4/lib/dry/types/options.rb @ line 16:
Owner: Dry::Types::Options
Visibility: public
Number of lines: 3

def with(new_options)
  self.class.new(*@__args__, options.merge(new_options))
end
>> show-method Dry::Validation::Guard#with

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/dry-validation-0.10.5/lib/dry/validation/schema_compiler.rb @ line 17:
Owner: Dry::Validation::Guard
Visibility: public
Number of lines: 3

def with(options)
  self.class.new(rule.with(options), deps)
end
>> show-method Dry::Validation::MessageCompiler#with

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/dry-validation-0.10.5/lib/dry/validation/message_compiler.rb @ line 30:
Owner: Dry::Validation::MessageCompiler
Visibility: public
Number of lines: 4

def with(new_options)
  return self if new_options.empty?
  self.class.new(messages, options.merge(new_options))
end
>> show-method Dry::Validation::Schema#with

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/dry-validation-0.10.5/lib/dry/validation/schema.rb @ line 67:
Owner: Dry::Validation::Schema
Visibility: public
Number of lines: 3

def with(new_options)
  self.class.new(self.class.rules, options.merge(new_options))
end
>> show-method Dry::Validation::Schema::DSL#with

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/dry-validation-0.10.5/lib/dry/validation/schema/dsl.rb @ line 75:
Owner: Dry::Validation::Schema::DSL
Visibility: public
Number of lines: 3

def with(new_options)
  self.class.new(options.merge(new_options))
end
>> show-method Dry::Validation::Schema::Rule#with

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/dry-validation-0.10.5/lib/dry/validation/schema/rule.rb @ line 174:
Owner: Dry::Validation::Schema::Rule
Visibility: public
Number of lines: 3

def with(new_options)
  self.class.new(node, options.merge(new_options))
end
>> show-method ROM::Changeset#with

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/rom-repository-1.3.1/lib/rom/repository/changeset.rb @ line 91:
Owner: ROM::Changeset
Visibility: public
Number of lines: 3

def with(new_options)
  self.class.new(relation, options.merge(new_options))
end
>> show-method ROM::CommandRegistry#with

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/rom-3.2.0/lib/rom/command_registry.rb @ line 106:
Owner: ROM::CommandRegistry
Visibility: public
Number of lines: 3

def with(new_options)
  self.class.new(relation_name, registry, options.merge(new_options))
end
>> show-method ROM::Commands::Graph#with

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/rom-3.2.0/lib/rom/commands/graph.rb @ line 78:
Owner: ROM::Commands::Graph
Visibility: public
Number of lines: 3

def with(new_options)
  self.class.new(root, nodes, options.merge(new_options))
end
>> show-method ROM::Relation#with

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/rom-3.2.0/lib/rom/relation.rb @ line 203:
Owner: ROM::Relation
Visibility: public
Number of lines: 3

def with(new_options)
  new(dataset, options.merge(new_options))
end
>> show-method ROM::Relation::Name#with

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/rom-3.2.0/lib/rom/relation/name.rb @ line 97:
Owner: ROM::Relation::Name
Visibility: public
Number of lines: 3

def with(relation)
  self.class[relation, dataset]
end
>> show-method ROM::Repository::RelationProxy#with

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/rom-repository-1.3.1/lib/rom/repository/relation_proxy.rb @ line 169:
Owner: ROM::Repository::RelationProxy
Visibility: public
Number of lines: 3

def with(new_options)
  __new__(relation, options.merge(new_options))
end
>> show-method ROM::Schema#with

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/rom-3.2.0/lib/rom/schema.rb @ line 373:
Owner: ROM::Schema
Visibility: public
Number of lines: 3

def with(new_options)
  self.class.new(name, options.merge(new_options))
end
>> show-method Dry::Logic::Operations::Abstract#new

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/dry-logic-0.4.1/lib/dry/logic/operations/abstract.rb @ line 30:
Owner: Dry::Logic::Operations::Abstract
Visibility: public
Number of lines: 3

def new(rules, **new_options)
  self.class.new(*rules, options.merge(new_options))
end
>> show-method Dry::Validation::PredicateRegistry#new

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/dry-validation-0.10.5/lib/dry/validation/predicate_registry.rb @ line 51:
Owner: Dry::Validation::PredicateRegistry
Visibility: public
Number of lines: 7

def new(klass)
  new_predicates = predicates
    .keys
    .each_with_object({}) { |key, res| res[key] = klass.instance_method(key) }

  self.class.new(external).update(new_predicates)
end
>> show-method Dry::Validation::Schema::Rule#new

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/dry-validation-0.10.5/lib/dry/validation/schema/rule.rb @ line 196:
Owner: Dry::Validation::Schema::Rule
Visibility: private
Number of lines: 3

def new(node)
  self.class.new(node, options)
end
>> show-method Dry::Validation::Schema::Value#new

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/dry-validation-0.10.5/lib/dry/validation/schema/value.rb @ line 146:
Owner: Dry::Validation::Schema::Value
Visibility: public
Number of lines: 3

def new
  self.class.new(registry: registry, schema_class: schema_class.clone)
end
>> show-method ROM::Changeset#new

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/rom-repository-1.3.1/lib/rom/repository/changeset.rb @ line 105:
Owner: ROM::Changeset
Visibility: public
Number of lines: 3

def new(relation, new_options = EMPTY_HASH)
  self.class.new(relation, new_options.empty? ? options : options.merge(new_options))
end
>> show-method ROM::Command#new

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/rom-3.2.0/lib/rom/command.rb @ line 399:
Owner: ROM::Command
Visibility: public
Number of lines: 3

def new(new_relation)
  self.class.build(new_relation, **options, source: relation)
end
>> show-method ROM::Mapper::AttributeDSL#new

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/rom-mapper-0.5.0/lib/rom/mapper/attribute_dsl.rb @ line 457:
Owner: ROM::Mapper::AttributeDSL
Visibility: private
Number of lines: 5

def new(options, &block)
  dsl = self.class.new([], @options.merge(options))
  dsl.instance_exec(&block) unless block.nil?
  dsl
end
>> show-method ROM::Processor::Transproc#new

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/rom-mapper-0.5.0/lib/rom/processor/transproc.rb @ line 401:
Owner: ROM::Processor::Transproc
Visibility: private
Number of lines: 3

def new(*args)
  self.class.new(*args)
end
>> show-method ROM::Relation#new

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/rom-3.2.0/lib/rom/relation.rb @ line 181:
Owner: ROM::Relation
Visibility: public
Number of lines: 11

def new(dataset, new_opts = EMPTY_HASH)
  if new_opts.empty?
    opts = options
  elsif new_opts.key?(:schema)
    opts = options.reject { |k, _| k == :input_schema || k == :output_schema }.merge(new_opts)
  else
    opts = options.merge(new_opts)
  end

  self.class.new(dataset, opts)
end
>> show-method ROM::Relation::Loaded#new

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/rom-3.2.0/lib/rom/relation/loaded.rb @ line 122:
Owner: ROM::Relation::Loaded
Visibility: public
Number of lines: 3

def new(collection)
  self.class.new(source, collection)
end
>> show-method ROM::Relation::ViewDSL#new
Error: Couldn't locate a definition for ROM::Relation::ViewDSL#new!
>> show-method ROM::Schema#new

From: /Users/johnbackus/.gem/ruby/2.4.1/gems/rom-3.2.0/lib/rom/schema.rb @ line 403:
Owner: ROM::Schema
Visibility: private
Number of lines: 3

def new(attributes)
  self.class.new(name, options.merge(attributes: attributes))
end
>>
```

So almost every `#with` instance method does the same thing and there are only two `#new` instance methods that have this behavior.

**Comment by flash-gordon** [comment]
@timriley we don't have any conventional methods for this in Ruby in general. However we have a couple here, in dry-rb/rom-rb (especially rom). Going with `new` will be consistent, we use it in `rom` like this. Going with `with`, well, sort of. And I have a reason for not having `merge`. It may seem fine to have the interface of `Hash`, but Ruby is a dynamically typed language and this makes things tough when it comes to type inference by just looking at a piece of code. I believe in this particular case with `dry-struct` it's better to know for sure.

**Comment by backus** [comment]
@flash-gordon checkout my examples above. It really seems like `#with` is used more consistently when an object is taking a hash of options and returning a new instance. `#new` seems to be used in cases where some other type of object is being provided and a new instance is returned.

**Comment by flash-gordon** [comment]
yes, but structs don't have options :) 
Anyway, just to be clear what this means
`.new` call is for replacing some kind of underlying core object. `relation` is a perfect example here, `relation.new` takes a new dataset and makes a new `Relation` instance with the provided dataset. It also accepts new options but they are not required. And `with` accepts only new options, the dataset will remain the same

**Comment by solnic** [comment]
@backus I know we have `#with` in more places, but the semantics is different, just like Nikita said we use `#new` to create new instances by passing in required constructor arguments; then we use `#with` exclusively for creating new instances by passing in optional constructor arguments. There are some sad exceptions though, like with have `ROM::Command#with` that accepts input, but it's going away in 4.0.

Here we don't have optional constructor arguments, so there's no need for `#with`. FWIW I like `#new` because it returns a new instance, just like class-level `.new`, and makes it more clear than `#with` that we're allocating a new object.

If it hurts your eyes, just add `alias_method :with, :new` to dry-struct and use whatever you prefer.

**Comment by timriley** [comment]
Thanks for the extra explanations @flash-gordon and @solnic. I'm satisfied now, happy to continue with `#new` :)

**Comment by solnic** [comment]
@timriley good to know :) I think we have more conventional methods used across the gems, so making them consistent would be nice. I plan to make a list of common patterns/methods, so that we can have an overview and we could look into places where things are not consistent and fix it (like this `ROM::Command#with`).

**Comment by backus** [comment]
Yup thanks for the clarification. I don't really even mind that much, just figured I would chime in on what I thought I had observed.

**Pull request merged**
