### PR TITLE
Sync attributes in descendant structs (fixes #51)

### LINKED ISSUE #51: Confusing behavior with inheritance and attr readers
We've found a bug which lets you define an attribute in a superclass after defining a descendant class, which results in attr reader defined, but corresponding attribute *is missing* in descendant schema.

Here's what I'm talking about:

``` ruby
require 'dry-struct'

class A < Dry::Struct
  class B < A
  end

  attribute :foo, 'string'
end

puts A::B.schema[:foo].inspect
# nil

puts A::B.instance_methods.include?(:foo)
# true
```

### PR DESCRIPTION
**Pull request by flash-gordon**

### CODE REVIEW

**Comment by solnic** [comment]
It's worth noting it will create major issues in rails and code reloading, in DataMapper it resulted in significant memory leaks.

**Comment by flash-gordon** [comment]
@solnic haha, good point, we shouldn't track `Dry::Struct`'s descendants at least. What comes to other problems I need to think it through...

**Comment by nannery** [comment]
@flash-gordon With this fix, if a superclass defines an attribute that a subclass *has already defined*, the superclass's definition will overwrite the subclass's definition -- is this what is intended? I feel like any descendent's definition should take precedence over its superclass(es).

```ruby
class A < Dry::Struct
  attribute :one, 'strict.string'
end
A.new one: 'ok'
# => #<A one="ok">

class B < A
  attribute :two, 'strict.string'
end
B.new one: 'foo', two: 'baz'
# => #<B one="foo" two="baz">

A.new one: 'ok' # still good
# => #<A one="ok">

A.attribute :two, 'strict.time'
A.new one: 'foo', two: Time.new
# => #<A one="foo" two=2018-01-25 16:37:44 -0000>

B.new one: 'foo', two: 'baz'
# Dry::Struct::Error: [B.new] "baz" (String) has invalid type for :two violates constraints (type?(Time, "baz") failed)
# from dry-struct/lib/dry/struct/class_interface.rb:185:in `rescue in new'
```

**Comment by flash-gordon** [comment]
You're right, this is not expected, although I thought it would raise an exception... Anyhow, this deserves a fix, I'll do it later today. 

And speaking of Rails-specific problems I think I'll just mention them in the docs.

**Comment by flash-gordon** [comment]
Fixed in https://github.com/dry-rb/dry-struct/commit/cbfcd760cb2436b820ddc8261fc196e13513c0f0

**Pull request merged**
