### PR TITLE
Support for wrapping constructors

### PR DESCRIPTION
**Pull request by flash-gordon**
See https://github.com/dry-rb/dry-types/pull/411

### CODE REVIEW

**Comment by pyromaniac** [comment]
@flash-gordon btw, there is one more thing to add support of: when you do `.default`, an attribute becomes not required. But in case of `.fallback` it does not. Is it possible to address it?

**Comment by flash-gordon** [comment]
Sure, 
```ruby
Dry::Types.define_builder(:defallback) { |type, default| type.fallback(defaut).default(default) }
safe_int = Types::Integer.defallback(30)
safe_int.() # => 30
safe_int.(:invalid) # => 30
safe_int.(20) # => 20
```

**Comment by pyromaniac** [comment]
Yeah, that's what I basically did. But should not `fallback` play the same way as `default` in case of structs? I think they are similar (while I realize that it is going to be challenging to implement it because default is a type and fallback is just a specific constructor)

**Comment by flash-gordon** [comment]
I thought about it. In general, I'm against mixing default with anything mostly because it was a PITA back in the days when predefined input schemas were a thing. In addition to that, now we have a straightforward way of defining custom type constructors so I decided to keep it this way. Another reason is some people may prefer the current behavior, they couldn't have it if `fallback` is triggered on missing input (like default), there's no simple way to make a type "stricter". Whereas wrapping `fallback` + `default` with a custom builder is a one-liner.

**Pull request merged**
