### PR TITLE
Add experimental support for pattern matching

### PR DESCRIPTION
**Pull request by flash-gordon**
This is Ruby 2.7+

Example:
```ruby
class User < Dry::Struct
  attribute :first_name, 'string'
  attribute :last_name, 'string'
  attribute(:address) do
    attribute :city, 'string'
    attribute :street, 'string'
  end
end

case user
in User({ first_name: 'Jack' })
  "It's Jack"
in User({ first_name: 'Alice' | 'Carol' })
  'Alice or Carol'
in User({ first_name:, last_name: 'Doe' })
  "DOE, #{first_name.upcase}"
in User({ first_name:, last_name: 'Doe' })
  "DOE, #{first_name.upcase}"
in User({ first_name:, address: User::Address({ street: 'Downing street' }) })
  "PM is #{first_name}"
end
```

With dry-monads 1.3:

```ruby
module Test
  class Operation
    include Dry::Monads[:result]

    def call(result)
      case result
      in Success(User({ first_name: }))
        "Name is #{first_name}"
      in Failure[:not_found]
        "Wasn't found"
      in Failure[error]
        "Error: #{error.inspect}, no meta given"
      in Failure[error, meta]
        "Error: #{error.inspect}, meta: #{meta.inspect}"
      end
    end
  end
end
```

### CODE REVIEW

**Comment by solnic** [comment]
This should be an optional extension. I actually don't like the fact it needs to have a deconstruct method. I hope they will change it in MRI ie it could be called `__deconstruct__`.

**Comment by flash-gordon** [comment]
Any reason why a language feature should an optional extension? Shouldn’t we turn other methods into extensions then?

**Comment by solnic** [comment]
First of all because it's not released yet, and secondly because the API should be extremely minimalistic because structs expose attributes and they can be anything, including the word `deconstruct`. I may actually report that this method should be `__deconstruct__` IMO.

**Comment by flash-gordon** [comment]
@solnic fair point, let's make it 2.7+ only and see what will be released in the end. I'm 👎 for making it optional since having a "deconstruct" attribute is a very special case anyway and there's a workaround `undef deconstruct`. If we make it an extension, users will have to guess why PM isn't working since it'll be a simple "NoMatchingPatternError" with no explanation why.

**Comment by solnic** [comment]
@flash-gordon OK sounds like a plan

**Pull request merged**
