### PR TITLE
Add pretty_print, so pry could show more readable structs

### PR DESCRIPTION
**Pull request by ojab**

### CODE REVIEW

**Comment by flash-gordon** [comment]
This should be an opt-in extension, see how they are implemented in `dry-validation` https://github.com/dry-rb/dry-validation/blob/master/lib/dry/validation/extensions.rb
`register_extension` is from `dry-core`: https://github.com/dry-rb/dry-core/blob/master/lib/dry/core/extensions.rb

Expected API:
```ruby
Dry::Struct.load_extensions(:pretty_print)
```

**Comment by flash-gordon** [comment]
The gem itself doesn't depend on `pry` neither `pretty_print` and this means no glue code should be loaded on loading the gem itself. I don't feel like pretty printing is a `dry-struct`'s concern since it can be handled on the `pretty_print` (or any other printer) side instead. I'm OK with adding an extension, though.

**Comment by ojab** [comment]
Done.

**Comment by flash-gordon** [comment]
Thank you!

**Pull request merged**
