### PR TITLE
Add struct composition

### PR DESCRIPTION
**Pull request by waiting-for-dev**
This feature would be a step towards using composition throughout dry-rb ecosystem, as we mentioned in https://github.com/dry-rb/dry-validation/pull/595 comments

### CODE REVIEW

**Comment by flash-gordon** [comment]
Why not reuse `Dry::Struct.attributes()` for that? I don't like `compose` since it implies you compose one with another and get something as a result. `.attributes` could check its argument and recognize a struct is passed. Or maybe add `.attributes_from` as a compromise

**Comment by waiting-for-dev** [comment]
In fact I see it just like that, you compose one struct with another struct and you get a third one. In a way it's also a composition in contrast of inheritance: instead of descending from a parent struct you use another one as argument. But, actually, I also like seeing composition in a very functional way, and here we don't have this facet, as neither pieces nor result are something callable. What do you think about `.merge` instead of `.attributes_from`?

**Comment by solnic** [comment]
Please rebase this on top of master, otherwise checks won't be run

**Comment by waiting-for-dev** [comment]
done @solnic

**Comment by flash-gordon** [comment]
@waiting-for-dev `merge` is used for hashes and works differently. What about `embed`?

**Comment by timriley** [comment]
My suggestion here is `attributes_from MyStruct`.

It fits with the attribute* naming scheme of the existing attribute declaration methods, and it also makes it pretty clear what’s happening without using a term that might otherwise come with baggage from different usages.

**Comment by flash-gordon** [comment]
I'm going to pull this in under `attributes_from`. We can continue the discussion because the next version will be quite big and I will test thoroughly before cutting a release

**Pull request merged**
